general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    
cloudFoundryDeploy:
  deployTool: 'mtaDeployPlugin'
  deployType: 'standard'
  cloudFoundry:
    org: '73523cbbtrial'
    space: 'dev'
    credentialsId: 'CF_CREDENTIALSID'
